services:
  postgres:
    image: postgres:14
    container_name: postgres-green-check
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: dev-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
